# sweep config
program: main.py
method: bayes
metric:
  name: average_perplexity
  goal: minimize
parameters:
  population_size:
    distribution: int_uniform
    min: 50
    max: 200
  elite_ratio:
    distribution: uniform
    min: 0.05
    max: 0.3
  max_age:
    distribution: int_uniform
    min: 5
    max: 50
  generations:
    distribution: int_uniform
    min: 50
    max: 200
  mutation_rate:
    distribution: uniform
    min: 0.1
    max: 0.5
  tournament_size:
    distribution: int_uniform
    min: 2
    max: 5
